-- the database is compliant to normal forms from n1 to n3
-- how ever there is a potential BCNF violation
-- Starting with Agents table 
--    AgentID INT PRIMARY KEY,
--    FirstName VARCHAR(50),
--    LastName VARCHAR(50),
--    Email VARCHAR(100) UNIQUE,
--    PhoneNumber VARCHAR(20),
--    HireDate DATE,
--    OfficeLocation VARCHAR(100),
--    Status ENUM('Active', 'Inactive') DEFAULT 'Active'